# Generated by Django 6.0.4 on 2026-05-08 12:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('calories_burn_per_min', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.IntegerField()),
                ('waist', models.IntegerField()),
                ('chest', models.IntegerField()),
                ('thighs', models.IntegerField()),
                ('mood', models.IntegerField(choices=[(0, 'Horrible'), (1, 'Bad'), (2, 'Neutral'), (3, 'Good'), (4, 'Great')], default=2)),
                ('success', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1024)),
                ('water_required', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('calories_per_100', models.IntegerField()),
                ('gl_index', models.IntegerField()),
                ('mass_per_descriptive_unit', models.IntegerField()),
                ('unit', models.IntegerField(choices=[(0, 'Piece'), (1, 'Plate'), (2, 'Glass'), (3, 'Spoon'), (4, 'Cup'), (5, 'Slice')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('calories_goal', models.IntegerField()),
                ('gl_goal', models.IntegerField()),
                ('activity_goal', models.IntegerField()),
                ('bucket_balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DailyPlanActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activity')),
                ('daily_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dailyplan')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('daily_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dailyplan')),
            ],
        ),
        migrations.CreateModel(
            name='MealFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.meal')),
            ],
        ),
        migrations.CreateModel(
            name='DailyPlanMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('daily_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dailyplan')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='UserFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField()),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.flower')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
